package com.matrix.entity.enums;

public enum PermissionEnum {
    MONITORING_DASHBOARD,
    CREATE_TICKETS,
    ASSIGN_TICKETS,
    VIEW_TICKETS,
    FIX_GLITCHES,
    ORACLE_REQUESTS,
    MANAGE_SENTINELS,
    CREATE_SIMULATIONS,
    SYSTEM_AUDIT,
    SELECT_CHOSEN_ONE,
    GENERATE_REPORTS,
    MANAGE_RESOURCES,
    VIEW_DOSSIER,
    CHANGE_STATUSES
}