import { Role } from "../types/types";

export type Ability =
  | "VIEW_DASHBOARD"
  | "KERNEL_CREATE_GLITCH"
  | "KERNEL_DETECT_CANDIDATE"
  | "TICKETS_VIEW"
  | "TICKET_CLASSIFY"
  | "TICKET_ESCALATE"
  | "TICKET_DECIDE"
  | "TICKET_FIX"
  | "TICKET_AGENT_COMPLETE"
  | "TICKET_REQUEST_REINFORCEMENT"
  | "TICKET_CLOSE"
  | "CANDIDATES_VIEW"
  | "CANDIDATE_FORECAST"
  | "CANDIDATE_BLUE_PILL"
  | "SENTINEL_STRIKE_REQUEST"
  | "REBOOT_MANAGE"
  | "ORPHANS_VIEW"
  | "ORPHAN_DECIDE"
  | "SIM_CREATE"
  | "REPORTS_VIEW"
  | "SIM_REPORT_REFRESH";

const map: Record<Role, Ability[]> = {
  ARCHITECT: ["VIEW_DASHBOARD","TICKETS_VIEW","TICKET_DECIDE","REPORTS_VIEW","REBOOT_MANAGE"],
  KERNEL: ["VIEW_DASHBOARD","KERNEL_CREATE_GLITCH","KERNEL_DETECT_CANDIDATE"],
  MONITOR: ["VIEW_DASHBOARD","TICKETS_VIEW","TICKET_CLASSIFY","TICKET_ESCALATE","TICKET_CLOSE","CANDIDATES_VIEW","SENTINEL_STRIKE_REQUEST","ORPHANS_VIEW","ORPHAN_DECIDE","REPORTS_VIEW","SIM_REPORT_REFRESH"],
  AGENT_SMITH: ["TICKETS_VIEW","TICKET_AGENT_COMPLETE","TICKET_REQUEST_REINFORCEMENT","CANDIDATES_VIEW","CANDIDATE_FORECAST","CANDIDATE_BLUE_PILL"],
  ORACLE: ["CANDIDATES_VIEW","CANDIDATE_FORECAST"],
  KEYMAKER: ["ORPHANS_VIEW","SIM_CREATE"],
  SENTINEL_CTRL: ["CANDIDATES_VIEW"],
  MECHANIC: ["TICKETS_VIEW","TICKET_FIX"]
};

export function has(role: Role, ...abilities: Ability[]) {
  const a = map[role] ?? [];
  return abilities.every(x => a.includes(x));
}

// для навигации: кто может открыть страницу
export const pageRoles = {
  dashboard: ["ARCHITECT","KERNEL","MONITOR"] as Role[],
  tickets: ["ARCHITECT","MONITOR","AGENT_SMITH","MECHANIC"] as Role[],
  candidates: ["MONITOR","AGENT_SMITH","ORACLE","SENTINEL_CTRL"] as Role[],
  reboot: ["ARCHITECT"] as Role[],
  orphans: ["MONITOR","KEYMAKER"] as Role[],
  reports: ["ARCHITECT","MONITOR"] as Role[]
};
